version: '3.8'

services:
  app:
    build: .
    container_name: express-api
    restart: unless-stopped
    env_file: .env
    ports:
      - "${PORT}:3000"
    depends_on:
      - mongodb
    networks:
      - app-network
    volumes:
      - .:/app
      - /app/node_modules

  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb-data: